### ISSUE TITLE
ComponentToolbar has key problem

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/LogicalSimulator#108]
```
next-dev.js?3515:20 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ComponentCategory`. See https://reactjs.org/link/warning-keys for more information.
    at ComponentRow (webpack-internal:///./src/components/SimulatorComponents/SimulatorComponentToolbar/componentToolbar.tsx:11:23)
    at ComponentCategory (webpack-internal:///./src/components/SimulatorComponents/SimulatorComponentToolbar/componentToolbar.tsx:42:22)
    at ComponentToolbar
    at div
    at div
    at div
    at div
    at SimulatorAddComponentDialog
    at TopToolbar (webpack-internal:///./src/components/SimulatorComponents/SimulatorTopToolbar/topToolbar.tsx:32:28)
    at div
    at main
    at Layout (webpack-internal:///./src/components/Layout/layout.tsx:17:26)
    at Simulator (webpack-internal:///./src/pages/simulator/simulator.tsx:24:26)
    at Logical (webpack-internal:///./src/pages/_app.tsx:18:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20742)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23635)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:70:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:215:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:406:27)
```

**Comment by UnsignedArduino** [comment]
Fixed in staging.
